### ISSUE TITLE
testing time

### ISSUE THREAD

**Issue by stark-xf** [dmaniry/deepIQA#13]
I tested the time of the model. It takes about 1.3s to process an image. Is that true?

**Comment by wunderwuzzi1975** [comment]
Your question is quite vague as you are neither providing any additional information on the hardware you are using nor on the image you are going to test. On my system (Xeon E5-2630v3, 16GB RAM, TitanX 12GB, Windows 7, Python 3.6) a NR test takes about 6 seconds to process an 12MP image (width =3968 pixel, height = 2976 pixel).
