### ISSUE TITLE
Using python3.5/3.6

### ISSUE THREAD

**Issue by omrysendik** [dmaniry/deepIQA#15]
Can this repository run with python3.5/3.6?
I can't seem to do so

**Comment by omrysendik** [comment]
Can't run due to cupy issues (and not the Python version)

**Comment by wunderwuzzi1975** [comment]
@omrysendik Which CUDA/CuPy/Chainer versions are you using? CUDA 9.2/CuPy 9.2/Chainer 4.5.0 on Windows 7 with Python 3.6 works flawlessly on my machine.

**Comment by omrysendik** [comment]
I'm using CUDA9.2, CuPy9,2, Chainer 5.1.0, Ubuntu 16.04 and Python 3.5

**Comment by wunderwuzzi1975** [comment]
@omrysendik What kind of CuPy issues are you experiencing?
