### ISSUE TITLE
Question about the inference result

### ISSUE THREAD

**Issue by Keetark** [dmaniry/deepIQA#5]
I think result of same two images should be 1 in FR-IQA.

But output of this evaluate.py isn't 1 

The followings are my command line instructions and the results.

Instruction : $python evaluate.py --model models/fr_tid_weighted.model --top weighted input.BMP ref.BMP
Result : 13.453525
Instruction : $python evaluate.py --model models/fr_tid_weighted.model --top weighted input.BMP ref.BMP
Result : 24.582006

The input and reference images are same and thus I expect that the result should be 1.
But, the results are quite big.
I didn't change any part of the codes.

I executed this code After installing requisites including chainer(v1.24.0) and scikit-learn on my linux machine with Ubuntu 16.04 LTS, 
I tried to do some inferences using your pretrained fr_tid_weighted.model and fr_tid_patchwise.model.

How can I interpret this results?

**Comment by HuiXu529731723** [comment]
Thank you. i have a problem now. when i input the 
$ python evaluate.py /home/xh@ct.lab/DeepIQA-master/tid2013/I01_01_1.bmp /home/xh@ct.lab/DeepIQA-master/tid2013/reference_images/I01.BMP --model /home/xh@ct.lab/DeepIQA-master/deepIQA-master/models/fr_tid_weighted.model
but the error exist
ValueError: volatile argument is not supported anymore. Use chainer.using_config
Could you give me some advice or directions about this problem? ? 
Is the version of chainer?

**Comment by HuiXu529731723** [comment]
@Keetark

**Comment by HuiXu529731723** [comment]
my version of chainer is 3.4.0

**Comment by wunderwuzzi1975** [comment]
@HuiXu529731723. I applied modifications to the code in order to use it with newer versions of chainer. I was able to get the code running using Ubuntu 16.04, Cuda 9.2/cupy-cuda92, and chainer 4.5.0. Feel free to clone my fork at [https://github.com/wunderwuzzi1975/deepIQA.git](url).
