### ISSUE TITLE
question about NR-IQA

### ISSUE THREAD

**Issue by ztt0821** [dmaniry/deepIQA#6]
Good job!!! I just begin to learn NR-IQA. Do I just need to run evaluate and nr_model?   We can't see the Models, so how to load the LIVE data into the programmer.

**Comment by wunderwuzzi1975** [comment]
To use NR-IQA with the LIVE model you need to call "python evaluate.py --model models/nr_live_patchwise.model --top patchwise Name_of_InputImage.JPG" if you want to estimate the global imagewise quality by simple average patch aggregation. In you want to use weighted average patch aggregation, you need to call "python evaluate.py --model models/nr_live_weighted.model --top weighted Name_of_InputImage.JPG". See Sec. III, Sub-Section A in the paper for more details on the difference between simple and weighted average patch aggregation.
