### ISSUE TITLE
TypeError: Can't broadcast (512, 1536) -> (512, 512)

### ISSUE THREAD

**Issue by kingrain213** [dmaniry/deepIQA#7]
when I run "python evaluate.py --model models/fr_tid_weighted.model --top weighted /data1/1_46.41_713.JPG"

I met "TypeError: Can't broadcast (512, 1536) -> (512, 512)"
what is the matter?
what should I do?

**Comment by wunderwuzzi1975** [comment]
fr_tid_weighted.model is a model for Full-Reference Image Quality Assessment, therefore you have to specify a reference image such as "python evaluate.py --model models/fr_tid_weighted.model --top weighted /data1/1_46.41_713.JPG /data1/Name_of_RefImage.JPG". If you don't have a reference image, you have to load a no reference model, f.e. such that "python evaluate.py --model models/nr_tid_weighted.model --top weighted /data1/1_46.41_713.JPG".
